### PR TITLE
feat: Automatic retrieval of repo name added

### PR DESCRIPTION
**Pull request by ramazansancar**

### CODE REVIEW

**Comment by ramazansancar** [comment]
I did some research on automatic retrieval of `WEBSITE_URL` data. However, I could not find a good result.

**Review by tristan-f-r — APPROVED** [review]

**Comment by ramazansancar** [comment]
@LeoDog896 I think the `WEBSITE URL` needs to be removed because there is no need for `.env.example` anymore.

**Comment by tristan-f-r** [comment]
I usually would, but I left it there in case someone needs to change its casing — they can always modify the workflow in their fork! (and the `.env.example` is mainly there for local development reference)

**Comment by ramazansancar** [comment]
It makes more sense the way you say. Thanks.

**Pull request merged**
